### ISSUE TITLE
Running inside of container gives error

### ISSUE THREAD

**Issue by 13hannes11** [StratusFearMe21/cargo-appimage#13]
When I run it in a container (podman or docker) I get the following error at the end of the build process:

```
fuse: device not found, try 'modprobe fuse' first
open dir error: No such file or directory
```

docker-compose:
```
version: "3"
services:
  rust-gtk-appimage:
    build: .
    volumes:
      - ../adwaita-demo:/mnt:z
    command: /bin/bash -c "cargo appimage"
```

Dockerfile:
```
FROM fedora:latest
ENV RUST_VERSION=1.58.1

RUN dnf install gtk4-devel gcc libadwaita-devel wget -y

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN . ~/.cargo/env
RUN ls $HOME/.cargo/env
ENV PATH=/root/.cargo/bin:$PATH
RUN rustup install ${RUST_VERSION}

RUN wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
RUN chmod +x appimagetool-x86_64.AppImage
RUN mv appimagetool-x86_64.AppImage /usr/bin/appimagetool

WORKDIR /mnt
RUN cargo install cargo-appimage

CMD ["/bin/bash"]
```
